config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :welcome
  root 'welcome#index'
  get 'paveh', to:'welcome#paveh'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end

	def paveh
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "KRYPTO 2 GO", root_path, class:"navbar-brand"%>
     
   <!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
    <div class="collapse navbar-collapse row" id="navbarNavDropdown">
      <div class="col-10">
        <ul class="navbar-nav">
          
          <li class="nav-item">
            <%= link_to "Paveh", paveh_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Exchanges
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </div>
        <div class="col align-content-end">
          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item active">
              <%= link_to "Log in", new_user_session_path, class:"nav-link"%>
            </li>
            <li class="nav-item active">
              <%= link_to "Sign up", new_user_registration_path, class:"btn btn-md btn-success nav-link"%>
            </li>
          </ul>
        </div>  
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KryptoPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		 <!-- <p class="notice"><%= notice %></p> -->
       <!-- <p class="alert"><%= alert %></p> -->
       <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/_carousel.html.erb
<div id="carouselHome" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%=image_tag("fotin.jpg", class:"d-block w-100 ", alt:"First slide" )%>
    </div>
    <div class="carousel-item">
      <%=image_tag("foto.jpg", class:"d-block w-100 img-responsive", alt:"Second slide" )%>
    </div>
    <div class="carousel-item">
      <%=image_tag("indexxx.jpg", class:"d-block w-100 img-responsive", alt:"Third slide" )%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselHome" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselHome" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome/index.html.erb
<%= render 'carousel'  %>

app/views/welcome/paveh.html.erb
<h1>Esta es otra pagina</h1>